### ISSUE TITLE
Two polling stations

### ISSUE THREAD

**Issue by PhilRumens** [DemocracyClub/UK-Polling-Stations#104]
There are two polling stations shown in this search:

http://pollingstations.democracyclub.org.uk/postcode/RG141aa/

Neither of them match the address in Your Polling Station.

**Comment by symroe** [comment]
Can you explain what the correct behavior should be here?  Is it the case that there are actually two polling stations?  Is it a problem with the underlying data?

**Comment by PhilRumens** [comment]
Will ask.

**Comment by PhilRumens** [comment]
OK, apparently the PSTN field against a postcode shows the right polling station.

The polling station won’t always be in the district they relate to. So it is perfectly normal that some polling districts won’t contain their own polling station and that some will have more than one.

This reflects that there isn’t always a suitable building for a polling station where they are required

**Comment by symroe** [comment]
This works connects to #107

**Comment by symroe** [comment]
![screen shot 2015-04-27 at 15 49 06](https://cloud.githubusercontent.com/assets/242329/7350033/f725e9ea-ecf4-11e4-875c-a08e6a2e2d94.png)

**Comment by symroe** [comment]
Fixed in #107
