### ISSUE TITLE
Re-evaluate javascript pipelining

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#1042]
Refs #1040 and https://github.com/DemocracyClub/polling_deploy/issues/6

Is the current approach right?
Should we be bundling?
Is there JS we can move out of templates and into .js files?

**Comment by symroe** [comment]
The new DC base theme uses Django pipeline and will minify and concat all JS files that are defined in a list in the project's settings. It's worth considering if this is the right thing to do, but we should wait until after we've updated the base theme.

**Comment by chris48s** [comment]
https://github.com/kevin1024/django-npm
