### ISSUE TITLE
Add info on voter ID trials for relevant areas in May 2018

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#1059]
Woking, Gosport, Bromley, Watford and Slough will be taking part in voter ID trials (see https://www.gov.uk/government/news/voter-id-pilot-to-launch-in-local-elections ), so the block 

```django
{% if territory == 'NI' %}
  <p>{% trans "You will need photographic identification" %}</p>
{% else %}
  <p>{% trans "You don't need any other form of ID" %}</p>
{% endif %}
```

will need to be updated to present the correct info for these areas

**Comment by JoeMitchell** [comment]
Update: Each council will have slightly different requirements for the ID.

**Comment by chris48s** [comment]
/remind me to check Woking and Slough on 8th February

**Comment by chris48s** [comment]
Swindon now participating, possibly replacing Slough: https://www.gov.uk/government/collections/voter-id-pilots

**Comment by chris48s** [comment]
https://www.swindon.gov.uk/info/20073/elections_and_voting/883/local_elections_may_2018_important_id_requirements_for_swindon_borough_voters/1

https://www.woking.gov.uk/council/election/idp

**Comment by chris48s** [comment]
This is what the EC are doing on YVM:

![screenshot at 2018-02-23 10 27 19](https://user-images.githubusercontent.com/6025893/36589804-7feb1f6c-1884-11e8-9dc4-0ed9d6c75629.png)

**Comment by chris48s** [comment]
Better link for Woking: https://www.woking.gov.uk/voterid
