### ISSUE TITLE
No polling station listed at http://pollingstations.democracyclub.org.uk/postcode/RG183BA/

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#106]

**Comment by symroe** [comment]
Looks like this is a feature to add to the code.

What's going on is that the polling district actually doesn't have a polling station within it at all:

Here is the location of the polling station that should be used, according to the data in the polling district:

![screen shot 2015-04-27 at 14 14 47](https://cloud.githubusercontent.com/assets/242329/7348266/f7ece35e-ece7-11e4-9945-2b2aed967a31.png)

As you can see here, the polling station is displayed on the map, but it's outside of the district:

![screen_shot_2015-04-27_at_14_14_55](https://cloud.githubusercontent.com/assets/242329/7348287/2e0b635c-ece8-11e4-9ada-33f0d8369b05.png)

**Comment by PhilRumens** [comment]
Yes, I'm told that's right. The polling station won’t always be in the district they relate to. So it is perfectly normal that some polling districts won’t contain their own polling station and that some will have more than one.

This reflects that there isn’t always a suitable building for a polling station where they are required.

**Comment by symroe** [comment]
Good to know!  The attached PR fixes that problem: https://github.com/DemocracyClub/UK-Polling-Stations/pull/107
