### ISSUE TITLE
Import Local Authority Districts (December 2015) Full Extent Boundaries in Great Britain

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#1085]
@chris48s - New Local Authority Districts (December 2015) Full Extent Boundaries in Great Britain available at http://geoportal.statistics.gov.uk/datasets/8edafbe3276d4b56aec60991cbddda50_1

**Comment by chris48s** [comment]
this is a new release but they're old boundaries
