### ISSUE TITLE
Self-serve uploads

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#1089]
https://democracyclub.org.uk/blog/2017/10/20/where-do-i-vote-tour/

You also have some more detailed notes. This is a longer term objective (i.e: after May 2018) but bear it in mind when looking at (for example) #1045. Try to implement checks in a way that they can be used in import scripts but could also be run against data when it is uploaded. Try to avoid coupling checks too closely to the import scripts or data quality report if possible.

**Comment by chris48s** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WhereDIV: Self-serve uploads](https://trello.com/c/KZRTAS1F/241-wherediv-self-serve-uploads)

**Comment by chris48s** [comment]
possible idea/s:

* review one district at a time showing station point and all properties assigned to it on a map (but don;t attempt to show/review >1 district at a time)
* highlight outliers eg. this property is significantly further than the other properties in its polling district

```
create materialized view pollingstations_resadd_pollsta
as
select ra.id, ps.internal_council_id, ra.address, ra.postcode, st_makeline(ps.location, ra.location) as geom
from pollingstations_pollingstation ps, pollingstations_residentialaddress ra
where ps.internal_council_id = ra.polling_station_id
```

![screenshot_from_2019-03-22_17-40-45](https://user-images.githubusercontent.com/6025893/54941177-161e1d00-4f24-11e9-8a57-bc9ad1fac258.png)

**Comment by chris48s** [comment]
MVP/initial feature-set for self-serve uploads. Initially to be piloted by our internal comms person with a view to rolling out to users:

- show the user a list of councils
- upload a file (or N files)
- check if we've got a CSV or TSV or something else
- check if it is a complete/parse-able file (hard error if its not)
- check it has a sensible number of rows (warn if not, but its not a hard error)
- check a sample of postcodes/addresses - do they match the target local auth?
- try and work out if its halarose/xpress/dc
- stick the file(s) on S3 in a sensible place
- raise an issue for it
- keep track of the fact that issue exists so that if we get a Version N+1 we can close the old issue and open a new one (needs persistent storage of some description)
- TODO: put it in some kind of queue where a bot can pick it up

..but where should it live?

A separate service:

- isolated from the WDIV prod environment
- needs its own storage/db
- data is harder to get:
  - councils: https://wheredoivote.co.uk/api/beta/councils.json
  - check num rows: Total Dwellings from 2011 Census is easy but AddressBase/ONSUD, not so much
  - check if addresses in file match target area: basically can't do it


Inside WDIV:

- all the data we need is just there:
  - Councils table
  - ONSUD, Addressbase
- we can put data in the logger DB
- we lose isolation:
  - what happens if we upload a massive file (e.g: Birmingham, Leeds: ~75Mb) and we're deployed on a t3.micro? Do we need to worry about:
    - memory usage
    - nginx timeout - 503
    - do we have to open the door to massive POST requests on the whole site?
  - do we want this to be able to affect the prod server performance? ( https://github.com/DemocracyClub/yournextrepresentative/issues/885 )
  - should this live on admin.wheredoivote.co.uk or something? Do some testing


Either way:

Upload massive file, do a bunch of processing on it, copy over a network, call some APIs
is a long process. For the UX of this to be acceptable, we need to make this somehow responsive/give the user feedback. Don't just sit there doing nothing. How do we do that well? Upload a file, bung some stuff in a celery queue + give the user a status page?
https://github.com/DemocracyClub/yournextrepresentative/pull/866/files
https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by GeoWill** [comment]
As far as the UX might an email work? It could look like:

- Require an email address to upload the file.
- Show a screen saying: 'Thanks for your upload, we'll let you know how it went...'
- Send an email once the file gets to the top of the queue and is checked. 

This would also save keeping lots of status pages live if doing a bunch of files at once (i.e. future internal comms person).

**Comment by symroe** [comment]
I reckon this is a good use case for the AWS Lambda upload to S3 triggers. You can set up a Lambda script to start when a new file is uploaded to S3, with the file passed as an argument to the script. The typical example is to resize an image to a thumbnail when the original is uploaded, but I think "unzip and triage a file" is in scope for that too.

It might not be worth it, if it involves getting the WDIV codebase working on Lambda (depending on the outcome of the above), but I reckon it's worth a shot thinking about. It might solve a load of hosting problems, and has the property of only being launched when used.

As for things like Total Dwellings – how precise is useful? I'd have though that seeing as it's a smoke test for truncated files then we could just create some static numbers against each council from time to time and accept that it'll be a bit wrong, but good enough? We're not aiming for perfection, just an automated belly-feel, right?

**Comment by chris48s** [comment]
Cheers for comments, both.


> As far as the UX might an email work?

Email is an interesting option. I hadn't thought of it, but it makes a lot of sense when you roll it out to councils. Maybe this needs a slightly different workflow for us internally (if you're uploading data from 20 councils per day, trying to debug problems by email could become clumsy).


> This would also save keeping lots of status pages live if doing a bunch of files at once (i.e. future internal comms person).

Yeah I reckon an internal admin user will need a single status page that reports lots of councils, whereas an external user would have a page that only reports status for their own council.


> I reckon this is a good use case for the AWS Lambda upload to S3 triggers

If you use lambda triggers, how do you get feedback from the lambda process? Presumably WDIV needs an API "callback" endpoint that the lambda function can call at the end to feed back what happened to WDIV? (by `POST`ing a json object, or something)


> It might not be worth it, if it involves getting the WDIV codebase working on Lambda

I think the main barrier to doing that would be that we'd have to abandon the "every front-end instance has its own DB instance" architecture and move to a RDS cluster or something. I'm not 100% opposed to that in principle, but its a lot of work, and I wouldn't want to embark on that change to support this one feature. If we're going to change that architecture, I'd want to evaluate the change/new setup on its own merits, if you see what I mean.


> As for things like Total Dwellings – how precise is useful?

So my ideal check here would be:

```
if {total lines in file} greater than {total residential dwellings from 2011 census} and smaller than {SELECT COUNT(*) FROM addressbase WHERE council_id=x}: warning
```

There will be times when that isn't right (e.g: because the file is complete, but the council isn't all-up, or we've got ~double the number of rows we expect because there are parish and district elections on the same day, or whatever), but usually the number of rows we expect is going to be in that window. The thing I'd be really checking for there isn't that the file is _truncated_, but that the council hasn't exported with a filter on or something (this class of problem sometimes happens).

Just thinking a step or two ahead, I reckon building in more checks at this stage of the process is going to be valuable (even if we don't have all of them initially). An example of another check we might add at this stage would be the classic "are any polling stations in the North Sea/on the other side of the country/etc?". Checks like that are much easier to perform if you're inside the WDIV codebase because all the helper functions you need already exist and all the data you need is there and updated regularly. If you're running in a microservice on lambda, those kind of checks are much harder to add at this point in the process.

**Comment by symroe** [comment]
> If you use lambda triggers, how do you get feedback from the lambda process? Presumably WDIV needs an API "callback" endpoint that the lambda function can call at the end to feed back what happened to WDIV? (by POSTing a json object, or something)

I reckon this is one for a conversation, as it's going to get confusing in this format, but I was initially thinking about keeping it to writing files back to S3. Basically, take a CSV, process it through some checks (and anything else we might want to do) and then save the file / report back to S3. This wouldn't need to be the full import process, it could just be a sanity check of the file, the number of rows, maybe the polling stations pulled out in to a list / map or something, but not anything that touches the WDIV database (or a copy of it).

**Comment by chris48s** [comment]
Agreed. I'd already earmarked it as something we should talk about as there are clearly tradeoffs to balance here, but the process of writing up my thoughts on it so far has been useful anyway :)

**Comment by chris48s** [comment]
Bit more thinking on this.. Wherever we put the upload form, big file uploads are a problem:

* If we upload to the same servers that are running production traffic, we have to allow massive POST requests, worry about memory usage, disk space etc.
* If we run a seperate microservice on lambda, Lambda has a [non-configurable limit](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) of 6Mb on the request payload.

The recommended way to deal with large file uploads on Lambda is to upload direct to S3 using by generating a pre-signed POST request (tl;dr: we use the AWS API to generate a time-limited token which allows the user to upload a _specific file_ to a _specific location only_ then give the user a form that `POST`s direct to a S3 endpoint using that token). Further reading: https://blog.webiny.com/upload-files-to-aws-s3-using-pre-signed-post-data-and-a-lambda-function-7a9fb06d56c1

Given the ultimate destination is an S3 bucket and doing this solves a problem which we need to solve in either case, this seems like a good thing to have a play with as a first step.

**Comment by chris48s** [comment]
Going to close this issue on the basis that we've done _something_ and the most helpful way to organise further work on this feature is by raising individual issue either:
* https://github.com/DemocracyClub/wdiv-s3-trigger/issues or
* https://github.com/DemocracyClub/UK-Polling-Stations/issues?q=is%3Aissue+is%3Aopen+label%3A%22file+uploads+%F0%9F%93%82%22
