### ISSUE TITLE
Improvements to Embed version

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#111]
The following were requested by @PhilRumens:

- [x] Permit `cross-origin framing`
- [x] Remove, “Where is my Polling Station?”. This will be the title of the page in our CMS, and I suspect it would work the same for most others embedding it too.
- [x] Remove, “We think we know where you should vote” and the Disclaimer. Whilst this is totally necessary on your site, it looks a bit strange on the site of the council holding the election.
- [ ] Not sure if this is possible, but a link to the council’s Twitter and/or lead page for the elections would be good.

**Comment by symroe** [comment]
> Not sure if this is possible, but a link to the council’s Twitter and/or lead page for the elections would be good.

Do you mean on the contact info for the council?

We can add that as a different ticket I think, as it would apply to every version of the site, embedded or not.  Is this what you mean?

**Comment by PhilRumens** [comment]
Yes, that's it. Additional contact info that could apply to every version of the site.
