### ISSUE TITLE
migrate the integration tests to...something else

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#1141]
Phantom JS isn't really actively developed anymore and Selenium are dropping support for it:

```
site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
```

it is also the flaky thing that makes the tests intermittently fail.

I've had the tests running on Firefox at one point, but I seem to remember there are a couple of useful things that headless Firefox doesn't support (or didn't at the time) that we would have had to remove. In javascript land the simple solution to this is electron, but I'm not sure that is an option for python/selenium. I'll poke headless Firefox/Chrome again at some point..

**Comment by symroe** [comment]
I've not used it at all, but https://pypi.python.org/pypi/pytest-bdd might be interesting when looking at this.

**Comment by symroe** [comment]
Mainly:

> Unlike many other BDD tools it doesn’t require a separate runner
