### ISSUE TITLE
Wrong polling station displayed

### ISSUE THREAD

**Issue by PhilRumens** [DemocracyClub/UK-Polling-Stations#118]
Searching for 

http://pollingstations.democracyclub.org.uk/postcode/rg183ba/

brings back the wrong polling station which is outside of the district.

**Comment by PhilRumens** [comment]
Seems to be returning "Cheddar Grove Primary School" which isn't in the district, for other searches:

http://pollingstations.democracyclub.org.uk/postcode/RG145LD/

**Comment by symroe** [comment]
This was fixed in https://github.com/DemocracyClub/UK-Polling-Stations/pull/115
