### ISSUE TITLE
Minor Styling Issue

### ISSUE THREAD

**Issue by PhilRumens** [DemocracyClub/UK-Polling-Stations#120]
![dc_0](https://cloud.githubusercontent.com/assets/4989597/7469309/edd322de-f309-11e4-9bf2-6f37a6ebf02a.png)

Styling on postcode search box (above) aligns top and left which is great, there's a bit of a margin or padding in the results page (below) though. Would you have time to align the results the same as the search box please?

![dc_1](https://cloud.githubusercontent.com/assets/4989597/7469321/17392542-f30a-11e4-8be3-70a5fba6a524.png)

**Comment by chris48s** [comment]
Closed by f01060c ?

**Comment by chris48s** [comment]
Closing as this relates to old theme - if there's any problems with the current theme, we can open a new issue.
