### ISSUE TITLE
East Lothian "phone your council" page says something weird

### ISSUE THREAD

**Issue by handelaar** [DemocracyClub/UK-Polling-Stations#123]
http://pollingstations.democracyclub.org.uk/postcode/EH216XB/

It's not hugely likely that a property valuation office situated 11 miles outside the authority's boundary is the right number to call.

Actual polling station data is available on the council website: http://www.eastlothian.gov.uk/download/downloads/id/9547/situation_of_polling_stations

**Comment by andylolz** [comment]
http://www.aboutmyvote.co.uk gives the same address / phone number for that postcode.

> Actual polling station data is available on the council website

That's true. In fact, these are available on all council websites. But none of them tell you where to vote i.e. provide a mapping from an address to a polling station.

**Comment by handelaar** [comment]
AboutMyVote is wrong. Council tax valuers can (and apparently do) register voters in Lothians but they have nothing at all to do with actually running elections -- which is why the web site of the linked org contains *no information whatsoever* about the election.

**Comment by andylolz** [comment]
I just tried the phone number – it works (person on the line was able to do address -> polling station lookup.)

**Comment by chris48s** [comment]
we've now changed the source for council contact data - closing
