### ISSUE TITLE
Become more accessible to potential contributors

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#137]
From @chris48s:

>  The repository is not as accessible as it could be to potential contributors in its current form. Personally I didn't have any issues getting started because I already had my machine set up as a dev box for mapit - so I already had all the necessary GIS/Postgres dependencies installed. I pretty much just cloned the repo and jumped in. I can see how someone who was willing to help with something like translations (for example) but isn't into the geography stuff would find it difficult to get started though. I would also be willing to do a bit more work on improving the documentation/setup instructions if you think this is of value.

**Comment by symroe** [comment]
Yes, this would be very valuable!

As I expect you can tell, this repo was thrown together quite quickly before the General Election 2015, and it was only really worked on by me and @davidmiller.  Anything to make it better for other people would be very welcome!

**Comment by davidmiller** [comment]
I seem to remember getting a fair way through a vagrant VM that just provisioned you the geography stuff and set up this site last March if that's at all of interest...

**Comment by chris48s** [comment]
>I seem to remember getting a fair way through a vagrant VM that just provisioned you the geography stuff and set up this site last March if that's at all of interest...

Yes I did also notice PR #100. Any reason that never went anywhere?
For now, I've submitted a PR with some tweaks to the docs which should hopefully clarify a bit.

**Comment by chris48s** [comment]
Closing this as we now have:
* Better install instructions
* Contributing guidelines
* Help wanted issues
etc

any further work relating to contributor accessibility should be raised as new more specific issue
