### ISSUE TITLE
Serve compressed static assets from a CDN

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#138]
From @chris48s:
> At the moment, you're serving up some reasonably large js files (especially leaflet.js) from /static - but jquery, bootstrap and leaflet could all be pulled in from content delivery networks to reduce bandwidth requirements and reduce server load a bit. This probably isn't the most urgent improvement but it is very easy to do, so it seems like an easy win. I'll knock up a PR for this at the weekend, including a fallback to /static to avoid introducing an additional point of failure.

:+1: This, plus I expect we can optimize the assets we're using anyway.  I'm planning on swapping to Foundation (to keep us in line with the other DC projects), and we might find that using the SASS version of that will reduce the overall file size.

**Comment by chris48s** [comment]
Finished/closed in new theme. :thumbsup:
