### ISSUE TITLE
change "we don't know of any upcoming elections" wording

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#1541]
Can we tweak this a bit to clarify that there might be parish/town/community election in some places

**Comment by JoeMitchell** [comment]
Might be controversial for us to define it this way, but how about...

>### **There are no major elections in your area...** 
>...but you may still have parish, town or community council elections. You can check [your local council website](https://councilymccouncilface) for more information. Or call them on 06510321561.
>
>_[Why don't we cover parish, town or community elections?](http://blogpost)_

**Comment by chris48s** [comment]
include a link to council website in this text
