### ISSUE TITLE
Import Local Authority Districts (April 2019) Full Extent Boundaries UK

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#1698]
@chris48s - New Local Authority Districts (December 2018) Full Extent Boundaries UK available at http://geoportal.statistics.gov.uk/datasets/ebfdb492eaa745bd845790f874c61cad_1

**Comment by chris48s** [comment]
http://geoportal.statistics.gov.uk/datasets/2b95585accc4437b97d766f31c5568cb_0
is an April 2019-dated release which includes the boundaries for the 5x new local auths.

Using this doesn't fix everything but will allow us to get rid of some of the hacks in `import_councils` to create the new boundaries from the union of the old ones.
Remember to update the alt_url in deploy repo and link the PR in #1630

**Comment by chris48s** [comment]
Going to put this one on hold for the moment as it also requires accounting for The Glasgow and North Lanarkshire Boundaries Amendment Order 2018 (`S12000049`/ `S12000050`)
