### ISSUE TITLE
Councils with their own polling stations finders

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#174]
Some councils have their own polling station search. For example, Hammersmith & Fulham have a polling station search on their website: https://www.lbhf.gov.uk/polling-stations-search (it isn't great because it doesn't seem to know which district you are in - it just lists stations near you).
I don't think we can extract the data from it conveniently (I think we would have to write a script to feed in postcodes one at a time and scrape the output), but if we don't get any data from Hammersmith & Fulham, should we link to their finder from the "we don't know where you should vote" page rather than just telling users to phone them?

As a related issue, if we don't manage to get as far as importing data for Carmarthenshire and Hackney (as noted by @davidmiller in issue #167 we should prioritise councils where we have complete data), they also have polling station maps on their websites that we could link to:
http://ilocal.carmarthenshire.gov.uk/my-nearest/
http://www.map.hackney.gov.uk/lbhackneymap/

**Comment by JoeMitchell** [comment]
While we're here, just spotted another one: http://www.wakefield.gov.uk/about-the-council/elections/polling-stations

(Again doesn't seem to understand local =/ necessarily your station)
