### ISSUE TITLE
Point NI postcodes to official site

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#179]
For the time being, http://www.eoni.org.uk/Offices/Postcode-Search-Results?postcode=BT5+7TQ is going to be far better than us.  We should detect if a postcode is in NI and offer a link to that site.

**Comment by chris48s** [comment]
Can someone post here when GLA announce the URL of their own polling station finder for London, please. We'll address the two as a single job.
RFC: Should we redirect all London postcodes to the GLA's site, or only in areas where we don't hold data? There are some London councils (e.g: Camden) who have worked with us to provide data who might like to see it served from this site.
Also linked to #174
