### ISSUE TITLE
Issues with DC Theme

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#187]
While I was doing some testing on the website, I found a few small niggles with the way that the website and the DC theme interact with each other. I haven't attempted to do anything about these because they aren't major problems and they potentially impact on other sites that use the theme (not just Polling Stations). I've raised an issue in case you think any of them are serious enough to warrant addressing.

* NUS Wales Themed version of the website throws a fatal error `Start tag “body” seen but an element of the same type was already open` in HTML validators because it defines 2 body tags - 1 in the DC base theme and then again in the Polling Stations NUS Wales theme:
```
<body >    
<body class="embed">
```
See https://validator.w3.org/nu/?doc=http%3A%2F%2Fwheredoivote.wales%2F
I've not seen any browsers which actually fail to render the page due to this, but valid markup would be ideal.

* Pages have empty title tags: `<title></title>`. This isn't terribly important for UX, but may impact on SEO a bit? Can this be moved into the site template without breaking other sites that use the base template?

* Header image feels like it should be a link, but it isn't - I keep clicking on it trying to get back to the home form. Because the header is defined in the base, it doesn't know what it should be a link to yet, so I understand why it isn't a link. This isn't a big problem - I think it is only annoying for me because I'm using the site in an unusual way - the typical user journey only involves searching for one postcode - not 50! ;) Maybe there should be a link back to home somewhere?

**Comment by symroe** [comment]
Fixed in b2e7c4c752b230c5f7671432edd23f894b8fb19c
