### ISSUE TITLE
'Coming soon' text for postcodes in councils that have provided data?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#199]
Ceredigion Council were a bit sad that they provided data but we haven't been able to use it (due to AddressBase lack thereof). 

They wondered if we could put a holding message for their pages. e.g. "This council has supplied the data. We're working on building maps with it." Or similar...

Not a high priority given lack of traffic I think.

**Comment by davidmiller** [comment]
Suspect minimal effort required and big relationship building win with CC...
