### ISSUE TITLE
Do we need a house icon for the start location?

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#203]
Esko suggested that we add a house location, and @JoeMitchell point out that the start looks a little empty now we have route planning on the map.

We should consider this, esp when useability testing.

**Comment by davidmiller** [comment]
Should also consider the case where the person lives very close to their polling station, and the two icons will be on top of one another with the map at the current zoom level.

**Comment by chris48s** [comment]
<img src="http://emojipedia-us.s3.amazonaws.com/cache/6d/31/6d316de129f2fc57ce987b49e715938b.png" /> ---------> <img src="http://emojipedia-us.s3.amazonaws.com/cache/df/1b/df1b892a76c6e48bd8b776f3d7af49a3.png" />

:thumbsup:
