### ISSUE TITLE
Copy edits for Welsh site

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#244]
From the translators at NUS Wales:

> I have spoken to my fellow Welsh translator colleagues and the errors are primarily concerned with the Welsh medium version of the site (bleibleidleisio.cymru). Here’s a few suggestions that we have come up with which are content related, as opposed to functionality related:
>  
> 1.    For each of the councils that data has not been provided for, there are council names that are in English and have not been translated into Welsh. These include Carmarthenshire Council and Swansea Council to name but a few that I have seen – I am unsure as to whether or not this is the same for all councils but a quick search on each of the Welsh council websites will provide you with both an English and Welsh name for both.
> 
> 2.    The word ‘Cyswllt’ has also been used in the Welsh text for the opening sentence of the Welsh site and it should be ‘Cysylltwch â Chyngor’ instead (which basically means “Contact (name of council area) Council”). This would avoid issues with Welsh mutations (a linguistic nuance) and generally look a lot more professional in the Welsh text. For example, ‘Cysylltwch â Chyngor Abertawe’ for ‘Contact Swansea Council’ and so forth.
> 
> 3.    There is also a blurb within the Welsh site where it says ‘We don’t have data for your area….’ for a few of the councils that data has not been provided for. Again, I am unsure as to whether or not this is the same for each council in Wales that hasn’t provided date but here is a generic Welsh translation that you can replace it with (of course, do not delete the number that is currently listed, as this is unique to each council):
> 
> Nid oes data gennym ni ar gyfer eich ardal chi.
> 
> Efallai y bydd esboniad ar eich cerdyn pleidleisio o ran ble i bleidleisio – fe gewch chi fe yn y post cyn yr etholiad.
> 
> Fel arall, gallwch gysylltu â’r cyngor gan ffonio nhw ar [council phone number]

**Comment by chris48s** [comment]
There's also some text we've added/edited but not translated yet. For example I added some error text in PR #258 which should ideally be translated. Might be a few other bits possibly?

**Comment by chris48s** [comment]
PR #270 as well.

**Comment by chris48s** [comment]
..and PR #288

**Comment by chris48s** [comment]
and PR #348
