### ISSUE TITLE
Make file uploads aware of elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#2547]
At the moment, we just stick files in a location on S3 based on upload timestamp.
This is probably fine unless a situation like we've had in 2017 and 2019 happens where we 2 elections back-to-back and we're receiving data for the second while we're still in the campaign period for the previous one. Then it will be very confusing and we'll want the ability to associate an upload with an election date (we don't really care if data relates to `local.2020-05-07` or `mayor.2020-05-07` or both - just that the relevant date of polling day is `2020-05-07`).

**Comment by symroe** [comment]
This is addressed in the WIP #3950 PR
