### ISSUE TITLE
Provide a suggestion/auto-correct invalid postcodes

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#2553]
https://github.com/DemocracyClub/UK-Polling-Stations/blob/6f9cf568d69857ba1f5a841c399d0b09153c5c9e/polling_stations/apps/data_collection/data_types.py#L148-L158

Look up the UPRN, if the match quality is good enough, auto-correct it, otherwise provide a suggestion. It might be that the easiest way to handle this is to move where we perform this check.

**Comment by GeoWill** [comment]
closed via  #2573
