### ISSUE TITLE
Import E07000006-South Buckinghamshire District Council

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#2585]
EMS: Xpress DC
Files:
- `E07000006/2020-02-17T12:12:27.576409/Democracy_Club__07May2020CSB.tsv`

**Comment by chris48s** [comment]
This is a single file with the data for both Chiltern and South Buckinghamshire in it.
Given these councils are both involved in the Buckinghamshire merger, wait on Aylesbury Vale/Wycombe before working out what to do with it.

**Comment by chris48s** [comment]
> On 1 April 2020, Aylesbury Vale, Buckinghamshire County Council, Chiltern, South Bucks and Wycombe District Councils will become a single Buckinghamshire Unitary Council. For electoral administration purposes the respective election teams in the former Aylesbury, Chiltern, South Bucks and Wycombe areas will continue to process electoral matters within their respective former district areas.
