### ISSUE TITLE
Docs on setting up develpment copy with addressbase

### ISSUE THREAD

**Issue by GeoWill** [DemocracyClub/UK-Polling-Stations#2601]
This doesn't apply to many people because of the licensing faff associated with addressbase. However it would still be good to document it.

**Comment by chris48s** [comment]
I reckon this is best done in the wiki, as opposed to the README.

What I've tried to do is keep the readme on this repo as a set of steps anyone who wants to contribute can follow to get a working dev environment up and running. Obviously they wouldn't be able to do import work, but its enough to be able to work on the website/api (this is actually one of the other useful things the ONSPD does! I forgot this the other day).

The wiki hold the more 'internal' stuff (how we deploy it + so on)

That's a pattern I've roughly tried to follow for all our repos, in fact. Readme is public-facing, wiki is more internal stuff.

**Comment by GeoWill** [comment]
https://github.com/DemocracyClub/UK-Polling-Stations/wiki/Setup-local-db-with-Addressbase
