### ISSUE TITLE
background / foreground colour combination makes “English / Cymraeg” link text difficult to read

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/UK-Polling-Stations#262]
This text is hard to make out:
![screen shot 2016-05-04 at 09 37 15](https://cloud.githubusercontent.com/assets/464193/15008995/e0098084-11db-11e6-9b61-13c6a682aaf0.png)

I’d like the foreground colour to be white.

**Comment by chris48s** [comment]
Given your high level of confidence in the theme change, I've proposed an alternative quick n dirty fix in PR #263

**Comment by andylolz** [comment]
Thanks @chris48s!
