### ISSUE TITLE
Import Southampton from INSPIRE WMS

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#264]
Shouldn't be too hard:

http://www.southampton.gov.uk/geoserver/wms?service=wms&version=1.1.1&request=GetCapabilities

**Comment by chris48s** [comment]
Stations KML:
http://www.southampton.gov.uk/geoserver/wms?LAYERS=SCC%3APOLLING_STATIONS&TRANSPARENT=TRUE&STYLES=Polling_Stations_Labelled&HOVER=false&FORMAT=kml&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A27700&BBOX=436000.0,108500.0,448000.0,118000.0&WIDTH=867&HEIGHT=426

Districts KML:
http://www.southampton.gov.uk/geoserver/wms?LAYERS=SCC%3APOLLING_DISTRICTS&TRANSPARENT=TRUE&STYLES=Polling_Districts_Labelled&HOVER=false&FORMAT=kml&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A27700&BBOX=436000.0,108500.0,448000.0,118000.0&WIDTH=867&HEIGHT=426

Had a cursory look and meta-data seems to contain ids linking stations and districts, so should be fine and will fit into the `BaseApiKmlKmlImporter` box.
