### ISSUE TITLE
Make the “give us data!” signup form a bit clearer

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/UK-Polling-Stations#272]
#### This thing is great:

![screen shot 2016-05-17 at 11 17 34](https://cloud.githubusercontent.com/assets/464193/15319151/5d0c6548-1c21-11e6-9fb8-ddce862d09a2.png)
#### …but it could be a bit clearer what I’m signing. Could it look a bit more petitiony, like this?

![screen shot 2016-05-17 at 11 20 03](https://cloud.githubusercontent.com/assets/464193/15319165/6db0a008-1c21-11e6-89a4-b50b33151765.png)

**Comment by chris48s** [comment]
this form was removed in #1052
