### ISSUE TITLE
Update links to external polling station finders (inc. removing link to LondonElects)

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/UK-Polling-Stations#274]
The London Elects polling station finder is now offline, so we should revert to providing London residents with the contact details of their local council.

**Comment by chris48s** [comment]
* As noted by @andylolz, we should stop sending users in London to London Elects as their polling station finder has been removed

* We hold data for Ceredigion council (e.g: http://pollingstations.democracyclub.org.uk/address/w06000008-1062-y-fro-a482-from-ystrad-aeron-to-the-entrance-of-aeron-valley-enterprise-park-felinfach-ceredigion-sa488af/ ) but if the user enters a postcode that we don't hold (e.g: a business postcode), we are still serving up the "coming soon" message: (e.g: http://pollingstations.democracyclub.org.uk/postcode/SA488YD/ ). The entry in `CustomFinders` should be removed so we serve the "we don't know - call your council" message instead.

* I thought we linked to Bristol's finder in May, but it seems we didn't (see http://pollingstations.democracyclub.org.uk/postcode/BS107AA/ ). Consider adding an entry for https://www.bristol.gov.uk/voting-elections/polling-station-finder

* Here's shortlist of other councils with finders that may be worth linking to (some of these are really quite good - other a bit more borderline, but all of these at least return a single unambiguous polling station address, present it in a relatively intelligible way and if they show a map, it has the polling station marked on it). If we don't get data from any of these areas, we might also consider linking to:
  * http://apps.exeter.gov.uk/dn2pollingstation/stationfinder.aspx
  * https://www.kingston.gov.uk/info/200263/voting_in_elections/635/where_to_vote_-_polling_districts_and_stations
  * http://app.ipswich.gov.uk/polling-station/
  * http://www.kirklees.gov.uk/beta/PollingStation/default.aspx
  * https://www.rbkc.gov.uk/yourcouncil/localdemocracy/postcodesearch.asp
  * https://www.lbhf.gov.uk/polling-stations-search
  * http://polling.breckland.gov.uk/  (mm.. this one's a looker!)
  * http://web.north-herts.gov.uk/WardsLookup/default.aspx
  * http://www.east-northamptonshire.gov.uk/info/200202/elections_and_voting/1738/find_your_polling_station
  * http://www.royalgreenwich.gov.uk/findpollingstation
  * http://www.sandwelltrends.info/web_mapping/find_my_polling_station.asp
  * http://www.southtyneside.gov.uk/article/15635/Find-your-polling-station
  * http://www.towerhamlets.gov.uk/lgnl/council_and_democracy/elections__voting/election_2016/polling_station_finder.aspx


@andylolz - any feedback on those or other suggestions for finders you're aware of that you reckon are worth linking to?
