### ISSUE TITLE
Incorrect escaping in some council data

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#2816]
e.g:
![Screenshot at 2020-08-19 16-44-40](https://user-images.githubusercontent.com/6025893/90662979-fab26100-e240-11ea-9c3a-467f50397f76.png)

![Screenshot at 2020-08-19 17-27-58](https://user-images.githubusercontent.com/6025893/90663306-6694c980-e241-11ea-8e0d-50e461749a1f.png)

etc

**Comment by symroe** [comment]
Sigh, of course! Thanks for reporting!

**Comment by symroe** [comment]
Fixed in https://github.com/DemocracyClub/UK-Polling-Stations/pull/2818/commits/f756f90a444e1fe3ef0bee072fc150cde9667735.

I decided to just unescape those two fields, as I think the other ones are unlikely to contain HTML entities.
