### ISSUE TITLE
Return UK 'territory' in postcode_location key

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#2823]
There are many cased where downstream users (via the devs.DC API) will want to know the territory* of a postcode / address.

For example, lots of election law is changing in Wales and Scotland with the new devolved powers they have.

If the `postcode_location` field on the API response contained a territory code, it would be easier for consumers to show content specific to the users country / territory.

I suggest a format like this:

```json
"postcode_location": {
        "type": "Feature",
        "properties": {
            "nation": "ENG"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                -2.20260988,
                51.74391142000001
            ]
        }
    },
```
This would be returned in all responses where a location is known, regardless of if a polling station is known.

## Implementation

Implementing this in `uk-geo-utils` is fairly easy - ONSUD and ONDPD have a `rgn` column that returns a pseudo GSS code for the "region". This starts with one of `E`, `S`, `W`, `N` like a normal GSS code. I've spoked an implementation of this here: https://github.com/DemocracyClub/uk-geo-utils/pull/17

The tricky part comes in this project, where we use `UprnToCouncil` as the `ONSUD_MODEL`. This is tricky for 2 reasons:

1. The table doesn't contain the `rgn` column, so we'd have to update the addressbase cleaning script to add it
2. It might have been possible to use the `lad` column for this when the value was a GSS code, but since #2818 the codes are now GDS register codes.

This might all change with #2738 of course, so we should consider this feature in that PR.

* is there a better term? One of England, Wales, Scotland or Northern Ireland - this is the term used by EE FWIW

**Comment by chris48s** [comment]
Nation is not best thought of as a property of postcode location - it makes more sense as a top-level property (like council, for broadly the same reason). `postcode_location` is a centroid point, but postcodes can be split across countries so if you think about a postcode like NP25 3SR that contains properties in >1 countries (10009561286 is in England, 10033359995 is in Wales). Assuming we remove the concept of "blacklist" postcodes you end up with.


`/address/10009561286`:
```json
"postcode_location": {
        "type": "Feature",
        "properties": {
            "nation": "ENG"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                -2.6820350923944667,
                51.83825015761978
            ]
        }
    },
```

`/address/10033359995`:
```json
"postcode_location": {
        "type": "Feature",
        "properties": {
            "nation": "WLS"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                -2.6820350923944667,
                51.83825015761978
            ]
        }
    },
```

which doens't really make sense.

Also, I'm unclear of the status of #2703 (abandoned? just having a rest?), but in the current model (i.e: pre- #2703 ) its possible that we _can_ assign a postcode/address to a council (and hence a country) but not be able to present a centroid for the source postcode (although I think #2703 removes that possibility).

**Comment by GeoWill** [comment]
If nation is to be a top level property like council then here's a possible implementation.
Attach a `nation` field to the council model to the council model. Populate it at import based on the `identifiers` which we get from the EC. 
Then add a `nation` field to the `/postcode/` and `/address/` endpoints in the same way `council` currently is. This means the `nation` field would be empty for postcodes split over multiple councils, and api users would need to get `nation` from the address objects. 

It might well be possible to check if `council.nation` is the same when there are multiple councils. But that will depend on what happens in #2703.

If we go with this I think the steps are:
- Add nation field to council model, and update council import script to populate it.
- Add nation field to address and postcode api endpoints and up date api docs.
- Check it gets pulled through to api aggregator and that the docs are up to date.

**Comment by chris48s** [comment]
> Add nation field to council model, and update council import script to populate it.

If you have a GSS code, `.nation` could just be an `@property` on `Council` that looks at the first char of the GSS code
