### ISSUE TITLE
Review the /about page and link it up

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#291]
From: https://github.com/DemocracyClub/UK-Polling-Stations/pull/190#issuecomment-198750228

@JoeMitchell wrote:
> Did make me realise we probably need an About, Privacy, Terms at some point. (I'm not sure what the legal requirements are). Probably a cookies thing (i wouldn't bother, but since WGovt are sponsoring). Should I make these issues and write some copy?

@chris48s wrote:
> An about/FAQ/privacy policy/terms and conditions page is probably a good idea. IMO a sentence or 2 about cookies on there is probably sufficient. There is already an about page at http://pollingstations.democracyclub.org.uk/about which you could use as a base to start from - it just isn't linked anywhere (obvious).

It would useful to review what's there at the moment - is it ok, does it need changing? Some additional text on the site and a bit of internal linking might also help a bit with search engine indexing. The top level sumary could also be used for the meta description (see issue #280). @JoeMitchell - thoughts on this?

**Comment by JoeMitchell** [comment]
Yes, I think this certainly warrants a review for 23 June text. Andy and I were chatting and saying a dedicated 'wheredoivote.uk' site (I can't remember the best domain we have) would be good for EU Ref. Then some words sound good. Will return to this later in the week! (Added to trello)

**Comment by symroe** [comment]
Linked to the DC site project page for this, that I think we should make better
