### ISSUE TITLE
Move data to it's own repo

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#303]
There is quite a lot of data in this repo now, making it slower to checkout the code itself. Also we might want to make a private repo with some of the data (I'm not sure about this, but it would be nice to have the option).

It's possible git isn't even the correct storage medium for this data anyway! Maybe we should look at some other sort of hosting.

**Comment by JoeMitchell** [comment]
Good points!

**Comment by chris48s** [comment]
I have ideas about this - lets discuss next time we do a hangout
