### ISSUE TITLE
Import NAY-North Ayrshire Council

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#3067]
EMS: Democracy Counts
Files:
- `NAY/2021-03-02T10:36:59.539487/Democracy Club - Polling Districts.csv`
- `NAY/2021-03-02T10:36:59.539487/Democracy Club - Polling Stations.csv`

**Comment by GeoWill** [comment]
NB All Ayrshires are using the same files.
