### ISSUE TITLE
Re-import E09000014-Haringey (or do nothing, cos unchanged?) 

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#313]
Haringey have confirmed that their data for 23 June is the same as 5 May, which it turns out we already have.

**Comment by JoeMitchell** [comment]
Hmm, actually, and curiously, Haringey have sent me a file that's dated 2016-04-04, so older than the one we already have (2016-04-05). So assume they sent me an older one by mistake. Or a misnamed one. But if there are any problems with the data we currently have, let me know and I'll upload the file they emailed me.

**Comment by chris48s** [comment]
Closing as the Haringey data is OK. It can either stay as it is or the import script is already tagged with `ref.2016-06-23` so if all the EURef importers get run in bulk, it will be re-imported.
Cheers
