### ISSUE TITLE
Import BUN-Burnley Borough Council

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#3147]
EMS: Xpress DC
Files:
- `BUN/2021-03-10T16:07:02.616665/Democracy_Club__06May2021.tsv`

**Comment by smsmith97** [comment]
Nothing to change.

**Comment by GeoWill** [comment]
https://github.com/DemocracyClub/UK-Polling-Stations/blob/971b3a4c175c219d1faab6610b158303ac595eca/polling_stations/apps/data_importers/management/commands/import_burnley.py#L9 

`"2021-03-10T16:07:02.616665/Democracy_Club__06May2021.tsv" != "2021-03-03T11:07:51.228358/Burnley Democracy_Club__06May2021 (1).CSV"`
