### ISSUE TITLE
Fix councils scraper

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#317]
`python manage.py import_councils` doesn't work anymore because
https://www.registertovote.service.gov.uk/register-to-vote/local-authority
has gone away. Not one to deal with now - should be deferred until after the EURef.

**Comment by symroe** [comment]
Looks like this is quite an easy fix, if we change the URL to `http://www.aboutmyvote.co.uk/ajax-content/search-voting-locations-by-districtcode?queries_distcode_query=E07000149` and update the parser.

**Comment by andylolz** [comment]
https://www.registertovote.service.gov.uk/register-to-vote/local-authority 404s, but the pages the scraper actually hits still seem to work i.e. https://www.registertovote.service.gov.uk/register-to-vote/local-authority/[GSS]

The only broken ones are Northern Ireland, but that’s _probably_ okay.

**Comment by symroe** [comment]
Is this still an issue? AFAICT it's working…
