### ISSUE TITLE
Import NWA-North Warwickshire Borough Council

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#3382]
EMS: Xpress DC
Files:
- `NWA/2021-03-26T10:37:06.912765/North Warwickshire Democracy_Club__06May2021.tsv`

**Comment by pmk01** [comment]
This file should also contain Nuneaton and Bedworth

**Comment by GeoWill** [comment]
I'll upload it for Nuneaton and Bedworth too.

**Comment by GeoWill** [comment]
#3506

**Comment by pmk01** [comment]
Ok, sorry, scratch that I, or Martyn, or both of us, were confused. I don't think they have sent Nuneaton yet. I will upload to Nuneaton if and when they do...
