### ISSUE TITLE
Import ROS-Rossendale Borough Council

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#3390]
EMS: Xpress DC
Files:
- `ROS/2021-03-26T12:02:38.065757/rossendale Democracy_Club__06May2021 (1).tsv`

**Comment by polling-bot-4000** [comment]
Updated
EMS: Xpress DC
Files:
- `ROS/2021-03-26T12:03:10.152976/Democracy_Club__06May2021.tsv`

**Comment by pmk01** [comment]
Er, i think you want to ignore the first of these and only use the second
