### ISSUE TITLE
Import BGW-Blaenau Gwent County Borough Council

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#3413]
EMS: Idox Eros (Halarose)
Files:
- `BGW/2021-03-29T15:39:51.593346/Blaenau Gwent polling_station_export-2021-03-29.csv`

**Comment by GeoWill** [comment]
closed in 838b66f0d8f82588b6c4fb30c38631dd1c04508b
