### ISSUE TITLE
Update South Cambridgeshire data from 5 May

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#343]
From Kelly: 

> We have just two changes to polling stations in South Cambs from 5 May:
> 
> PD1
> Grantchester
> Grantchester Communal Centre, Tabrum Close, Grantchester
> CB3 9NW
> 
> OC1, OC2
> Milton & Milton detached
> Milton Community Centre, Coles Road, Milton, Cambridge
> CB24 6BL
> 
> All other details remain the same as supplied ahead of May's local elections.

**Comment by chris48s** [comment]
Closed by 13b8e7b
