### ISSUE TITLE
League table doesn't work on live site

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#357]
https://wheredoivote.co.uk/league_table/

This is another one I can't reproduce locally

**Comment by symroe** [comment]
Not sure why, but there are only 2 objects in the DB, as per the view.

How are the DataQuality objects created? Is it ad import time?

I think the solution here is to use the `logger` database for the league table – all records are imported properly there. I'll update the router accordingly…

**Comment by chris48s** [comment]
one day....

**Comment by chris48s** [comment]
closing because we binned this feature: https://wheredoivote.co.uk/league_table/
