### ISSUE TITLE
Remove date of referendum from results page

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#360]
![your_polling_station___wheredoivote_](https://cloud.githubusercontent.com/assets/8096305/18505626/02253e78-7a60-11e6-964a-e6637ec2709c.png)

I tried to look for this in the codebase to see if I could PR the removal. But alas, I couldnae find it.

**Comment by chris48s** [comment]
This was done and merged in https://github.com/DemocracyClub/UK-Polling-Stations/pull/347/commits/5c202e9f9f7d1a0cbf7a64d0b67bedcc34dda1a6 - I just don't think the live site reflects the current repo.

Might need to poke @symroe about getting it deployed.

**Comment by symroe** [comment]
Deployed
