### ISSUE TITLE
Fix map tiles (again?) 

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#365]
This came up before: https://github.com/DemocracyClub/UK-Polling-Stations/issues/345

But seems to have re-appeared:

>Just a heads up that the map on the whocanivotefor postcode results page is not displaying.
>e.g. https://whocanivotefor.co.uk/elections/N15%206RH/

**Comment by chris48s** [comment]
Moved to https://github.com/DemocracyClub/WhoCanIVoteFor/issues/67
