### ISSUE TITLE
List of things we think need UX testing

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#367]
Not comprehensive, but a starting point for anyone who wants to test specific elements of the UX:
## 'my address is not in the list' button (address picker page)

@chris48s said: 

> When I was testing this I found a couple of times I selected an address then clicked 'my address is not in the list'. I'm not sure if this is because the buttons aren't laid out in the most sensible way, or just because I was running through a bunch of different test cases quickly.
> 
> If you get a chance to do any UX testing at any point, it might be worth reviewing the layout of those buttons:
> - Do users find this confusing?
> - Are the buttons the right way round?
> - Should one be left-aligned and one right-aligned?
> - Should the buttons be different sizes or colours?

**Comment by symroe** [comment]
Lots about addresses here https://designpatterns.hackpad.com/Addresses-CgrMSGRAhRc#:h=Examples-on-GOV.UK

**Comment by mtsk3000** [comment]
hi guys (my first response!)

Done a bit of UX review and think there are a couple of quick things we can do to tighten it up a bit

![image](https://cloud.githubusercontent.com/assets/20727101/25562566/f714d5fa-2d80-11e7-89a3-ff72b19ad8e6.png)

The key thing is the lack of information hierarchy. We got 2 big main call-to-actions here, while only one is relevant at a time (ie if I have not select my address, the "i have selected..." btn should be disabled/hidden). The current flow is that both btn are clickable, and if you click "find my polling station" without selecting an address, the site then handle the flow error by showing showing an error msg.

A potentially better solution could be this:
![image](https://cloud.githubusercontent.com/assets/20727101/25562579/abfe1a94-2d81-11e7-989d-2538974602a1.png)
Nothing selected

![image](https://cloud.githubusercontent.com/assets/20727101/25562582/d0e66cbc-2d81-11e7-885c-21444fa50b29.png)
Address selected - I am not entirely sure if the "X Remove selection" bit is a bit over-designing, but I think we should at least allow the user to click the selected option to unselect, that allows the user to access the "My address is not in the list" button again (not typical behaviour I know, but why now 😛 ). The tick icon just adds a bit more confident and positivity to the "find my polling station" button to make decision a bit easier. every little helps.

Hope that helps!

**Comment by chris48s** [comment]
@mtsk3000 - Cheers for having a look at this for us. I've submitted PR #750 for review based on your ideas.

**Comment by JoeMitchell** [comment]
Thanks Max, these make sense to me! I think it'd help David's why-can't-i-double-click thing too!
