### ISSUE TITLE
Do we need a 'last-updated' notice?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#404]
I was emailing a council person to tell them 'not to worry, we don't assume the data is accurate for more than one election'. But in fact, the Cardiff data, e.g., is all still up there. And if there was a by-election that we're not aware of, it might not longer be accurate.

Do we need something like the attached. (But probably better designed. :D) 
![your_polling_station___wheredoivote_](https://cloud.githubusercontent.com/assets/8096305/20487675/3d186290-affc-11e6-94f6-397a95c96d22.png)

**Comment by chris48s** [comment]
Would it seem reasonable to shove a similar message to the one on https://whocanivotefor.co.uk/ on the front page?

**Comment by JoeMitchell** [comment]
I think so — there's a (small) risk we're getting hits from folks with
by-elections receiving data still lying around from 2016, and theoretically
the correct data could have changed versus what we have.

And we do say that we don't use data for more than one election.

**Comment by andylolz** [comment]
I think the current message on https://whocanivotefor.co.uk is good. How would you change it, @chris48s?

Re. the proposed change here: can I suggest “your poll card” rather than “a poll card”, and a date e.g. “last updated on 30 May 2016” rather than “last updated for the [EU referendum]”.

**Comment by chris48s** [comment]
@andylolz - Nothing too dramtic. Just substitute "elections in May 2016" for "referendum in June 2016", *possibly* remove the link to candidates site(?) but keep the blog link. I'll knock up a quick PR taking into account discussion in this issue..

**Comment by andylolz** [comment]
> Nothing too dramtic. Just substitute "elections in May 2016" for "referendum in June 2016"

Well… The site doesn’t appear to contain any information. So neither of those is correct, really.

> _possibly_ remove the link to candidates site(?)

Searching for a postcode on [the candidates site](https://candidates.democracyclub.org.uk) currently takes you back to whocanivotefor, which contains no information. So yeah, either remove links to it, or change this behaviour so it is actually a May 2016 archive.

**Comment by chris48s** [comment]
https://wheredoivote.co.uk/ - sorted

**Comment by andylolz** [comment]
That’s https://wheredoivote.co.uk, not https://whocanivotefor.co.uk. Were we talking at cross purposes the whole time?

In any case, +1 good fix.
