### ISSUE TITLE
Even simpler tech requirements page

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#418]
Feedback from an Electoral Services Manager: 

> having read the technical requirements [I] must confess to being a little bamboozled by what I need to provide! 

This refers to: https://democracyclub.org.uk/projects/polling-stations/technical/

A non-tech volunteer could have a look over this?

**Comment by chris48s** [comment]
This doesn't fully cover it, but reading it again, one thing that occurs to me is we're using quite a lot of acronyms and jargon that we aren't defining (JSON, KML, UPRN...WTF?). We can probably clarify this by adding some links for more info, so for example:

> A spatial dataset describing the locations of polling stations in an open geographic format (e.g: KML, GeoJSON, SHP)

..becomes..

> A spatial dataset describing the locations of polling stations in an open geographic format (e.g: [KML](https://developers.google.com/kml/), [GeoJSON](http://geojson.org/), [SHP](https://en.wikipedia.org/wiki/Shapefile))

That's probably a good first step...

**Comment by chris48s** [comment]
applies to content that has been replaced by https://democracyclub.org.uk/projects/polling-stations/upload/
