### ISSUE TITLE
Assign councils to domain based on more than the councils email address

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/UK-Polling-Stations#4220]
I would like the ability to assign councils to any domain - for example, Wandsworth and Richmond staff use @wandsworthandrichmond.gov.uk domains for their personal emails. At present the user has to create an account first, and then we attach it to them, which is hard to explain.

**Comment by pmk01** [comment]
Good questions. Not a lot, I suspect. If we need to punt any uploader work, this is probably it.

**Comment by symroe** [comment]
Ok, I suggest we do it in code for now then, as that's a quick win. Can you make a list of domain -> council ID for each non-default domain you know about, and we'll add that to the logic that assigns users to councils?

**Comment by symroe** [comment]
Is this done?

**Comment by VirginiaDooley** [comment]
> Is this done?

Yes I believe so. Completed with https://github.com/DemocracyClub/UK-Polling-Stations/pull/4958
