### ISSUE TITLE
RFC: Thoughts on improving the API

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#423]
As discussed in the hangout the other night, here's some thoughts on improving the API. For the moment, I'm just focussing on the `/postcode` endpoint flow. There's probably also stuff that needs to happen with the `/pollingstations` and `/pollingdistricts` endpoints (particularly districts - I think the `/pollingdistricts` endpoint in its current form is pretty useless), but there's already an absolute wall of text to read here, so we'll save that for another issue. 

# TL;DR version

* Should a valid response always parse into a consistent object at the top-level, or is it OK for the top-level keys of the object to vary in different cases?
* Error responses should definitely return a suitable HTTP status code, not `200 OK` as they do at the moment.
* Should valid responses include `"error": false` so that can always be checked?
* Should we add a `/address` endpoint so that we can call https://wheredoivote.co.uk/api/address/1-foo-street-bar-town.json (for example)
  OR..
* Should this be dealt with by modifying the `/pollingstations` endpoint so that we can call something like https://wheredoivote.co.uk/api/pollingstations.json?council_id=X01000001&polling_station_id=FOO ?
* Is it actually sensible to maintain a distinct API, or would it be better to simply expose the controller layer of the application as json?
* Should we version the API?

# All the gory details

OK, so at the moment, if I call https://wheredoivote.co.uk/api/postcode/CF105AJ.json (polling station known from postcode) I get back:
```json
{
  "postcode_location": {
    "latitude": "51.46518039304887",
    "longitude": "-3.1657202682046206"
  },
  "polling_station_known": true,
  "polling_station": {
    "council": "https://wheredoivote.co.uk/api/councils/W06000015/",
    "postcode": "",
    "address": "Portacabin, County Hall, County Hall, Atlantic Wharf, Butetown, Cardiff",
    "location": {
      "latitude": "51.469852462940835",
      "longitude": "-3.162477184225377"
    }
  },
  "council": {
    "council_id": "W06000015",
    "council_type": "UTA",
    "mapit_id": "2639",
    "name": "Cardiff Council",
    "email": "electoralservices@cardiff.gov.uk",
    "phone": "029 2087 2034",
    "website": "https://www.cardiff.gov.uk/ENG/Your-Council/Voting-and-elections/pages/default.aspx",
    "postcode": "CF10 4UW",
    "address": "City of Cardiff Council\nCity of Cardiff Council\nCounty Hall Atlantic Wharf\nCardiff",
    "location": {
      "latitude": "51.46988759266582",
      "longitude": "-3.163464746032237"
    }
  }
}
```

.. and if I call https://wheredoivote.co.uk/api/postcode/SW1A1AA.json (we don't know) I get back:

```json
{
  "postcode_location": {
    "latitude": "51.50086373251905",
    "longitude": "-0.14320717529002294"
  },
  "polling_station_known": false,
  "council": {
    "council_id": "E09000033",
    "council_type": "LBO",
    "mapit_id": "2504",
    "name": "Westminster City Council",
    "email": "electoralservices@westminster.gov.uk",
    "phone": "020 7641 2730",
    "website": "https://www.westminster.gov.uk/contact-electoral-services",
    "postcode": "SW1E 6QP",
    "address": "Westminster City Council\nElectoral Services\nWestminster City Hall\n64 Victoria Street\nLondon",
    "location": {
      "latitude": "51.49755195883463",
      "longitude": "-0.137377277846367"
    }
  }
}
```

I think these outputs are basically ok, although there is maybe an argument that we should actually be returning an empty addresses array `"addresses": []` on both those endpoints and an empty polling_station object `"polling_station": {}` in the "we don't know" case so that a valid response from a call to `/postcode` always parses into a consistent object.

That would make the outputs more like:

```
{
  "postcode_location": {
    ...
  },
  "polling_station_known": true,
  "polling_station": {
    ...
  },
  "council": {
    ...
  },
  "addresses": []
}
```

```
{
  "postcode_location": {
    ...
  },
  "polling_station_known": false,
  "polling_station": {},
  "council": {
    ...
  },
  "addresses": []
}
```

Not sure if that's better or not - thoughts on this?

Calling https://wheredoivote.co.uk/api/postcode/foo.json responds with:

```json
{
  "polling_station_known": false,
  "error": "Mapit error 400: Postcode 'FOO' is not valid."
}
```

..which I think is fine in terms of output, but it returns a `200 OK` status which is not cool. The response header should have an error code rather than a `200 OK`. Also maybe good responses should also include `"error": false` so that can always be checked?

The other case we need to deal with is where a postcode is ambiguous and we need to return a list of addresses. At the moment, if I call https://wheredoivote.co.uk/api/postcode/CF157RP.json (for example), I get back:

```json
{
  "postcode_location": {
    "latitude": "51.54630720254116",
    "longitude": "-3.262801815353187"
  },
  "polling_station_known": false,
  "council": {
    "council_id": "W06000016",
    "council_type": "UTA",
    "mapit_id": "2599",
    "name": "Rhondda Cynon Taf Council",
    "email": "electoralservices@rhondda-cynon-taf.gov.uk",
    "phone": "01443 490100",
    "website": "http://www.rctcbc.gov.uk/en/councildemocracy/democracyelections/elections-electoralregister/elections-electoralregister.aspx",
    "postcode": "CF37 1NY",
    "address": "Rhondda-Cynon-Taff Council\nUnit 2\nMaritime Business Park\nMaritime Industrial Estate\nPontypridd",
    "location": {
      "latitude": "51.59575820114506",
      "longitude": "-3.349613058685383"
    }
  },
  "addresses": [
    {
      "address": "1 RHYMNEY COTTAGES, TAFFS WELL, CARDIFF",
      "postcode": "CF157RP",
      "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
      "polling_station_id": "PHE"
    },
    {
      "address": "2 RHYMNEY COTTAGES, TAFFS WELL, CARDIFF",
      "postcode": "CF157RP",
      "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
      "polling_station_id": "PHE"
    },
    {
      "address": "3 RHYMNEY COTTAGES, TAFFS WELL, CARDIFF",
      "postcode": "CF157RP",
      "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
      "polling_station_id": "PHE"
    },
    {
      "address": "4 RHYMNEY COTTAGES, TAFFS WELL, CARDIFF",
      "postcode": "CF157RP",
      "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
      "polling_station_id": "PHE"
    },
    {
      "address": "THE OLD FORGE, OLD PARISH ROAD, TAFFS WELL, CARDIFF",
      "postcode": "CF157RP",
      "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
      "polling_station_id": "PHC"
    }
  ]
}
```

There's a couple of ways we can go with this. One of these would be to add an `/address` endpoint and then make the output something like:

```
{
  "postcode_location": {
    ...
  },
  "polling_station_known": false,
  "polling_station": {},
  "council": {
    ...
  },
  "addresses": [
    {
      "address": "1 Foo Street, Bar Town",
      "postcode": "CF157RP",
      "url": "https://wheredoivote.co.uk/api/address/1-foo-street-bar-town.json",
    },
    .....
    {
      // something that corresponds to "my address is not in the list"
      "url": "https://wheredoivote.co.uk/api/councils/W06000016/",
    }
  ]
}
```

I think in the last case, we can just link straight to the `/councils` endpoint rather than add a separate `/we_dont_know` endpoint.

The other approach is we just don't bother with a `/address` endpoint, keep the current style of output and

```json
{
  "address": "THE OLD FORGE, OLD PARISH ROAD, TAFFS WELL, CARDIFF",
  "postcode": "CF157RP",
  "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
  "polling_station_id": "PHC"
}
```

means we should call something like:
https://wheredoivote.co.uk/api/pollingstations.json?council_id=W06000016&polling_station_id=PHC
(and update the `/pollingstations` endpoint to accept a query of that nature).

..or alternatively, make that explicit in the output and return (for example)

```json
{
  "address": "THE OLD FORGE, OLD PARISH ROAD, TAFFS WELL, CARDIFF",
  "postcode": "CF157RP",
  "council": "https://wheredoivote.co.uk/api/councils/W06000016/",
  "polling_station": "https://wheredoivote.co.uk/api/pollingstations.json?council_id=W06000016&polling_station_id=PHC"
}
```

# A Different Idea

All of the above works on the assumption that we are maintaining the API and website as 2 different entities. I think we've done a pretty good job of allowing the api code and website to share the same logic and stuff, but fundamentally if we add info that we want to surface via both the website and the API, there are 2 places we need to do that.

Another different approach to exposing the site's goodies to developers would be to go with the 'make the website **be** the API' approach. So basically what I'm envisaging here is that if you call https://wheredoivote.co.uk/postcode/CF105AJ.json or just call https://wheredoivote.co.uk/postcode/CF105AJ with an `Accept: application/json` header, you get back the content of https://wheredoivote.co.uk/postcode/CF105AJ in json form instead of html. In order to do that, we generate the `context` object, json encode it and just slap it in a HTTP Response object.

This would make the flow of the address selection case go:

* https://wheredoivote.co.uk/postcode/CF157RP.json
* https://wheredoivote.co.uk/address_select/CF157RP.json
  Then either
* https://wheredoivote.co.uk/address/w06000016-phe-1-rhymney-cottages-taffs-well-cardiff-cf157rp.json
  OR
* https://wheredoivote.co.uk/we_dont_know/CF157RP.json

(as with the website)

Obviously there's tradeoffs here. This would need a bit of work to:
* make the outputs consistent
* make the flow between endpoints clear from the json
* adapt routing/controllers to accept different headers/extensions + respond accordingly

..but it provides some advantages:

* making changes to the website automatically updates the API and makes the changes available to developers - we don't need to do things in 2 places
* API can easily share view helper code and serve up stuff like links for walking directions, which we don't currently do

The main disadvantage is it makes it difficult to do stuff like version the API. I don't think we currently do this, but once we've actually got active users (other than WCIVF), this is something that we arguably should be doing. Also it might make it more difficult to do things like rate-limiting/API keys as you'd only want to apply that stuff to the json outputs and not the HTML. Maybe those things make this a bad idea.

Would welcome feedback on any/all of the above, but this is probably a good place to start the conversation.

**Comment by vincelee888** [comment]
came here from @symroe's tweet. i'd love to get involved and help. my two cents:

consistent responses are definitely the way to go, avoid any surprises and use the standards. don't have consumers fishing around for booleans that represent _errors_ and _found_, use the appropriate http status codes. if things don't exists, just return an empty collection.

it feels like the endpoint should really be ```polling_stations/```, which would give you other calls:

```polling_stations/?postcode={postcode}``` search by postcode - returns a collection of polling stations
```polling_stations/{postcode_id}``` returns a single specific polling station

the objects returned by this endpoint would be the ```address``` you currently return  

councils also seems to be a different endpoint.

dylan beattie did a great talk on RESTful APIs: https://github.com/dylanbeattie/RealWorldREST/tree/master/slides in which he talked about how to manage it when consumers need different levels of info from an endpoint, and helping them navigate the structure of your api.

hope that helps!

**Comment by mvl22** [comment]
We'd love to be able to resurrect our 'cycle to your polling station' page using external data:
https://www.cyclestreets.net/blog/2010/05/05/cycle-to-your-polling-station/

Things that we find most useful in APIs:

* Please return geographical data as GeoJSON, not flat JSON. It makes little difference for using it in a data parsing context, but for showing it on a map (e.g. Leaflet.js) this makes it is vastly easier - almost no coding required.

* Please enable filter by bbox (W,S,E,N) order, i.e. enable matching using `&bbox=w,s,e,n`, which can be used for a map set to close zoom levels.

These two would mean third-party implementers (like us) can create a browse-the-map interface with very little work.

**Comment by chris48s** [comment]
I hadn't focussed when I initially posted this that Sym would tweet this issue, so my original post probably both lacks some of the context necessary for a wider audience and also may be a bit too specific in some ways. Also I suspect this discussion is going to expand a bit beyond the original scope.

At the moment, the API has 4 endpoints:
* `/councils` (e.g: https://wheredoivote.co.uk/api/councils/W06000016.json )
* `/pollingstations` https://wheredoivote.co.uk/api/pollingstations.json (this doesn't accept any parameters at the moment, but it needs to)
* `/pollingdistricts` https://wheredoivote.co.uk/api/pollingdistricts.json (this also doesn't accept any parameters and doesn't include the boundaries so is basically pointless at the moment)
* `/postcode` (e.g: https://wheredoivote.co.uk/api/postcode/CF157RP.json )

There are also arguments for and against adding a `/residentialaddress` endpoint, but that's probably best abstracted for now..

`/councils`, `/pollingstations` and `/pollingdistricts` are fundamentally for exposing the raw data, whereas `/postcode` is for exposing the 'service' (for want of a better word). It was fairly hastily knocked up last year to surface polling station data for use on [Who Can I Vote For](https://whocanivotefor.co.uk/), but all of these endpoints have various problems and we're looking make improvements so that API can be used by a wider audience.

Thanks for the input so far. To respond to a few comments..


@vincelee888
> consistent responses are definitely the way to go
> if things don't exists, just return an empty collection

Yep - think this confirms my opinion that `"addresses": []` and `"polling_station": {}` should be included where they are empty/not applicable.

> use the appropriate http status codes

:+1: Completely agree - just to clarify, error responses returning `200 OK` is a problem we need to fix. It wasn't really a question :)

> dylan beattie did a great talk on RESTful APIs

Cheers for the recommendation - I'll check it out.

@mvl22
> Please return geographical data as GeoJSON, not flat JSON

Great point. I think GeoJSON is the correct output format (or at least a correct output option) for the `/pollingstations` and `/pollingdistricts` endpoints - and *maybe* `/councils`.

So, for example on the `/pollingstations` endpoint, the output would look something roughly like:

```
{
  "type": "FeatureCollection",
  "features": [

    ....

    {
      "type": "Feature",
      "id": "er... need to think about this",
      "geometry": {
        "type": "Point",
        "coordinates": [
          51.469852462940835,
          -3.162477184225377
        ]
      },
      "properties": {
        "council": "https://wheredoivote.co.uk/api/councils/W06000015/",
        "postcode": "",
        "address": "Portacabin, County Hall, County Hall, Atlantic Wharf, Butetown, Cardiff",
      }
    },

    ....

  ],
  "crs": {
    "type": "EPSG",
    "properties": {
      "code": "4326"
    }
  }
}
```

..and so on for `/pollingdistricts` and maybe `/councils`. That example might not actually be strictly valid syntax, but you get the point.

In terms of the `/postcode` endpoint, it might be more difficult to bash that into a geojson format given it (potentially) contains a mix of geographic and non-geographic data. Either way, its a useful point for us to take into account.

Tangentally related question: @symroe - in a `council` object, there's a `location` field with a point in it, but I'm not sure it is actually...useful. Does that get used on WCIVF? I'm wondering if it actually needs to be there.

> Please enable filter by bbox

If implemented, this probably applies to the `/pollingstations` and `/pollingdistricts` endpoints rather than `/postcode`. Again, potentially useful suggestion.

> We'd love to be able to resurrect our 'cycle to your polling station' page using external data:
https://www.cyclestreets.net/blog/2010/05/05/cycle-to-your-polling-station/

Based on the info in your blog post, I think (an improved version of) the `/pollingstations` endpoint might meet your needs but https://www.cyclestreets.net/journey/places/pollingstations/ is a `404`. As a potential user of open polling station data, it might be good to find out a bit more. Maybe @symroe or @JoeMitchell could ping you an invite to join our Slack if interested?

**Comment by mvl22** [comment]
> Maybe @symroe or @JoeMitchell could ping you an invite to join our Slack if interested?

Sure, thanks; I'll DM @symroe the particular e-mail address to use.

**Comment by chris48s** [comment]
Another one to lob in here.. mainly so I remember it as I'm working on stuff.
At the moment we are only logging API usage on the `/postcode` endpoint, but once calling something like https://wheredoivote.co.uk/api/address/1-foo-street-bar-town.json or https://wheredoivote.co.uk/api/pollingstations.json?council_id=X01000001&polling_station_id=AA is part of the finding process, we will need to be logging that or it will skew the found/not found stats unfairly in favour of not found. Also more generally it would be nice to have stats on general api usage.
This may require some bashing of the log data structure as the `LoggedPostcode` model assumes every log event is attached to a postcode.

**Comment by chris48s** [comment]
We've just deployed a beta API serving up last year's data at
https://wheredoivote.co.uk/api/
Over the coming weeks, we will be trialling this with data partners who will be using the API for the elections in May. This includes the Electoral Commission who plan to [use our data on YourVoteMatters](https://ukelectoralcommission.wordpress.com/2017/02/06/helping-voters-find-out-where-to-vote/). Note that the API is currently serving up data from last year and is currently in beta. As such, the data available will definitely be changing and is **not suitable for production use**. The API itself may also see changes based on user feedback before it becomes stable.

Based on this I am going to close this issue. Any specific feedback from data users can be raised as new issues.

@mvl22
All points and boundaries available via the API are now serialized as GeoJson features, which should make the data easier to work with.
We have chosen not to implement a BBOX filter. From the perspective of directing users to polling stations, it is important to note that it is not enough to show the user all nearby polling stations because voters must vote at their assigned polling station. This is determined by the voter's registered address.
Using the [polling station finder API](https://wheredoivote.co.uk/api/#polling-station-finder), you can use the `/postcode` and `/address` endpoints to find a user's assigned polling station based on their address (if we hold data) or info on how to contact their council (if we don't).
Where possible, this will give you a GeoJson point object describing the location of the polling station. This data could be used to plan a cycle route from the input postcode to the polling station location using a service like [Google's directions API](https://developers.google.com/maps/documentation/directions/intro) in much the same way as we are doing on our site with walking directions.
If you're interested in using the data on this basis, feel free to have a play with the beta and if you have questions, hit us up in #polling-stations on Slack.
