### ISSUE TITLE
Camarthenshire - Can we scrape it ?

### ISSUE THREAD

**Issue by davidmiller** [DemocracyClub/UK-Polling-Stations#48]
I refer to your request for information, which was received on 9th March, 2015 and has been dealt with under the Freedom of Information Act 2000.
 
The specific information you requested was as follows:
The data on the location of polling stations your council manages that will be open on May the 7th 2015
The shapefiles of the polling districts your council manages
In response, the locations of all polling stations within Carmarthenshire are published by the Council on its website, using our iLocal mapping (click on Council and Democracy and then the box for Polling Stations):
 
http://ilocal.carmarthenshire.gov.uk/my-nearest/
 
The polling stations are shown on iLocal as a point – we do not have shapefiles for the districts they cover.
 
Under Section 21 of the Act, a public authority is not obliged to provide information which is already reasonably accessible to the applicant, which in this case is via our website as set out above.
 
As I am refusing to provide information on the basis that it is already published, please consider this email to be a formal notice of refusal as required by Section 17 of the Act.

**Comment by davidmiller** [comment]
Maybe we can scrape the iLocal data points and boundaries?

**Comment by chris48s** [comment]
Yes we can :)
