### ISSUE TITLE
Unnecessary text on Northern Ireland results

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/UK-Polling-Stations#4957]
NI postcode results return:

![Screenshot 2023-01-31 100044](https://user-images.githubusercontent.com/61510609/215728863-da080e7f-5d55-467c-a6c9-a569093c6cc2.png)

The final sentence needs to be deleted. We provide the contact details on a card further down the page.

What does the result look like when we have data for NI? Does the unfinished sentence appear there, too?

**Comment by Bekabyx** [comment]
Because it was a very quick fix, and to keep things consistent across our various lookups, we've decided to keep the text but fix it so that the phone number actually shows.
