### ISSUE TITLE
Non-postcode-format text breaks the search field a bit

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/UK-Polling-Stations#4977]
Identical issue to https://github.com/DemocracyClub/WhoCanIVoteFor/issues/1505

![Screenshot 2023-02-13 111407](https://user-images.githubusercontent.com/61510609/218443388-1f5ba712-3781-4a75-8c69-6c938eed278c.png)

**Comment by GeoWill** [comment]
https://github.com/DemocracyClub/UK-Polling-Stations/pull/4980
