### ISSUE TITLE
TEST Import BDF-Bedford Borough Council for 2023-05-04

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#5148]
EMS: Xpress DC
Files:
- `BDF/2023-05-04/2023-03-09T13:02:35.083946/Democracy_Club__04May2023.csv`

**Comment by VirginiaDooley** [comment]
Test for https://github.com/DemocracyClub/UK-Polling-Stations/pull/5050
