### ISSUE TITLE
'Get walking directions' doesn't work in embedded version

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#523]
This is happening! 

![Sad gif](http://g.recordit.co/Vv9E8yIn8m.gif)

Maybe there's a 'Open in New Window' option? Or maybe should just remove the option?

**Comment by chris48s** [comment]
Reproduced this locally. I think google maps detects that you're trying to `<iframe>` it and blocks you. Applying the changes proposed in PR #417 fixes this (along with other issues), so if/when those changes are merged that will resolve this problem.

**Comment by chris48s** [comment]
Fixed in PR  #417
