### ISSUE TITLE
Change Coventry Borough Council to City Council

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#525]
>Also, when a postcode isn’t found, can we change Coventry Borough Council to Coventry City Council please? (see https://wheredoivote.co.uk/embed/postcode/CV15RR/ )

**Comment by chris48s** [comment]
Re-running the councils scraper should fix this:
https://www.registertovote.service.gov.uk/register-to-vote/local-authority/E08000026
but currently blocked on PR #441

**Comment by chris48s** [comment]
Fix now deployed: https://wheredoivote.co.uk/postcode/CV15RR/
