### ISSUE TITLE
Import S12000036-Edinburgh

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#551]
I think the data is here:

* https://edinburghcouncilmaps.info/arcgis/rest/services/Misc/INSPIRE/MapServer/7
* https://edinburghcouncilmaps.info/arcgis/rest/services/Misc/INSPIRE/MapServer/28

They link to maps made using this data on their website, so we can assume it's kept up to date.

**Comment by chris48s** [comment]
* Morph scraper for API
* Review this, [Dundee](https://morph.io/wdiv-scrapers/DC-PollingStations-Dundee) and [Fife](https://morph.io/wdiv-scrapers/DC-PollingStations-Fife) in the context of #554

**Comment by chris48s** [comment]
https://morph.io/wdiv-scrapers/DC-PollingStations-Edinburgh
