### ISSUE TITLE
Dynamic example postcodes

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#575]
The problem:

We have a hard coded example postcode on the home page. This only works if we have data imported for the current election for that postcode.

Also, in the white-label or embedded versions, it would be nice to have a postcode for that area.

Suggestions:

1. Pull the postcode in to settings and set that when deploying.
2. Maintain a list of postcodes we know we have data for (by grabbing a postcode from the addresses, or picking a random postcode in a district for shapes). Then we can have a list of postcodes, one per area. We can then pick them randomly on the home page (or pick once per server load, e.g. keep it in memory).
3. For embedded, allow passing an example postcode in the query string of the URL
4. For white-label, configure this per white label site

**Comment by chris48s** [comment]
Yes - I've thought before that allowing councils who embed to specify an example postcode for their own area would be a useful value-add.

**Comment by chris48s** [comment]
I think the example postcodes need to be slightly "curated" - you want to pick one such that your example sort of showcases the optimum situation. So you want one that doesn't require an address choice, maps to a valid station, definitely has a point (so you get map + directions) and so on. Randomly picking one doesn't necessarily guarantee those things. Picking a 'nice' postcode is the sort of thing task that would be natural to do while writing the import script.
