### ISSUE TITLE
Import NWA-NWA for 2024-05-02

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#6118]
EMS: Xpress DC
Files:
- `NWA/2024-05-02/2024-02-06T22:09:52.124723/Democracy_Club__02May2024.tsv`

**Comment by polling-bot-4000** [comment]
Updated
EMS: Xpress DC
Files:
- `NWA/2024-05-02/2024-02-07T08:53:01.197969/Democracy_Club__02May2024.tsv`

**Comment by awdem** [comment]
https://app.asana.com/0/1205951895246773/1206599177238821/f
