### ISSUE TITLE
Example postcode works...but also doesn't

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/UK-Polling-Stations#6192]
At time of writing, Lewisham has data online for a 7 March by-election. The [Lewisham page](https://wheredoivote.co.uk/uploads/councils/LEW/) on WDIV uploader shows me this: 
![Screenshot 2024-02-19 095742](https://github.com/DemocracyClub/UK-Polling-Stations/assets/61510609/0c7b91f3-ec76-46a7-bead-59758d18b8d8)

When I click the 'Example page' for SE4 2HH, it shows me a polling station (no address picker).

But! when I enter that postcode manually, I'm told to Contact London Borough of Lewisham and not given a station.

What's going on here?

**Comment by GeoWill** [comment]
That postcode isn't an example postcode. It's the postcode for the station. You had me worried.

**Comment by GeoWill** [comment]
Does this look better/less confusing: 
![image](https://github.com/DemocracyClub/UK-Polling-Stations/assets/20044500/7908fa17-6821-4387-8a9a-a3976b2b08fa)
