### ISSUE TITLE
Deal with Polling districts that share a Polling place

### ISSUE THREAD

**Issue by davidmiller** [DemocracyClub/UK-Polling-Stations#73]
> There are 20 wards in Salford, which are split into 144 polling districts designated by a code made up of two letters, the first letter designates the ward. For example the Cadishead ward (A) is split into 6 polling districts (AA, AB, AC, AD, AE & AF).  Each polling district has a corresponding polling station. Please note that some polling districts share a polling station; for example districts “BA” & “BD” share “Irlam Community Centre Locklands Lane / Ferryhill Road.

**Comment by symroe** [comment]
It's possible that #107 fixes this, but more testing is needed.  And we need to update the importers for each council.

**Comment by chris48s** [comment]
52e6deea contains 2 examples of this that work correctly.

**Comment by chris48s** [comment]
Closing as we do now deal with this correctly. If anyone disagrees, re-open
