### ISSUE TITLE
Update we're not sure messaging: 

### ISSUE THREAD

**Issue by davidmiller** [DemocracyClub/UK-Polling-Stations#74]
... to suggest people can use their polling card.

Stretch goal: 

> @symroe "Maybe a nice icon that looks a bit like a polling card"

**Comment by tfgg** [comment]
![image](https://cloud.githubusercontent.com/assets/103349/13983165/fd54c6b0-f0e5-11e5-8f42-3bd20559b0c1.png)

How's that? No nice icon yet...

**Comment by chris48s** [comment]
wording has changed and changed again - closing
