### ISSUE TITLE
Fonts on home page

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/UK-Polling-Stations#741]
![image](https://cloud.githubusercontent.com/assets/8096305/25502563/01e6c81a-2b8f-11e7-8c04-79caca0d3359.png)

I think all this text should be the same font. 

The two lines behave differently (see below) when squished to mobile too... they should behave the same way! 

![image](https://cloud.githubusercontent.com/assets/8096305/25502647/64113142-2b8f-11e7-9457-d9976bd9fd6e.png)

**Comment by chris48s** [comment]
Given we want to redo the styling on this site so it is all a bit more


![](https://democracyclub.org.uk/static/dc_theme/images/logo-with-text-2017.png)


I'm going to suggest we park styling tweaks and revisit as part of that process..

**Comment by JoeMitchell** [comment]
Could a quick fix just be to apply the same style to both lines?

**Comment by chris48s** [comment]
review after #1040

**Comment by chris48s** [comment]
closed in #1137
