### ISSUE TITLE
Email me my polling station

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#751]
@jf1 suggests:

> Could DC offer an email reminder (on polling day) to people who use WhereDIV or WhoCIVF
> A box for "Enter your email address if you'd like us to send you a reminder on polling day" should go just under this

**Comment by JoeMitchell** [comment]
Relatively low priority, I think... In that those who use Who or Where are
not the kind of people who need a reminder... and we already do (not
terribly good) election alerts...

...but maybe worth testing, see who uses it.
