### ISSUE TITLE
Import MRY-Moray Council for 2024-07-04

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#7589]
EMS: Democracy Counts
Files:
- `MRY/2024-07-04/2024-06-06T13:28:18.455137/Democracy Club - Polling Districts MWNS.csv`
- `MRY/2024-07-04/2024-06-06T13:28:18.455137/Democracy Club - Polling Stations MWNS.csv`

**Comment by polling-bot-4000** [comment]
Updated
EMS: Idox Eros (Halarose)
Files:
- `MRY/2024-07-04/2024-06-07T15:31:30.247085/Eros_SQL_Output003-Moray.csv`

**Comment by BobbiWesterman** [comment]
Eros file from Grampian VJB.

**Comment by polling-bot-4000** [comment]
Updated
EMS: Idox Eros (Halarose)
Files:
- `MRY/2024-07-04/2024-06-17T14:56:43.378925/MRY_combined.csv`
