### ISSUE TITLE
Import SWT-Somerset Council (formerly Somerset West & Taunton) for 2024-07-04

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#7834]
EMS: Idox Eros (Halarose)
Files:
- `SWT/2024-07-04/2024-06-17T16:33:01.558703/Eros_SQL_Output012.csv`

**Comment by blacktyger** [comment]
Can't run the import due to error:

`RelatedObjectDoesNotExist: Council has no geography.`
