### ISSUE TITLE
Cache write ops?

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/UK-Polling-Stations#810]
At the moment every front-end server instance writes a log entry to a single shared RDS instance on every request.

There is scope to make this shared DB server less of a bottleneck by cacheing the log entries locally and then sending them up to the logger DB in batches, but we need to be careful not to lose data when dropping an instance out of the cluster.

**Comment by symroe** [comment]
These two commits might be helpful:

https://github.com/DemocracyClub/WhoCanIVoteFor/commit/494c2d0aaa45b67653d69787f1c834f76671abb5

https://github.com/DemocracyClub/WhoCanIVoteFor/commit/4d15a81a05ca7965b4ebc53b19caa2959d23f218
